"""empty message

Revision ID: bb2109de56d8
Revises: 2f54a4aede7c
Create Date: 2016-02-29 00:23:22.595907

"""

# revision identifiers, used by Alembic.
revision = 'bb2109de56d8'
down_revision = '2f54a4aede7c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('image_filename', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'image_filename')
    ### end Alembic commands ###
